### ISSUE TITLE
Change proc name so it shows up in ps / top / activity monitor as btlock instead of python3 / python

### ISSUE THREAD

**Issue by skela** [aude/btlock#1]
I think it's probably possible using something like this:

https://pypi.org/project/setproctitle/

**Comment by skela** [comment]
![screenshot from 2018-11-25 16-33-42](https://user-images.githubusercontent.com/58268/48980966-f8ed5500-f0cf-11e8-9e4d-bb35711c4d6d.png)

**Comment by aude** [comment]
I am surprised that the process is not called `btlock` if you run `./btlock`.

After having researched it a bit now, it seems that this is a common situation for all scripting languages ([python](https://stackoverflow.com/questions/564695/is-there-a-way-to-change-effective-process-name-in-python), [ruby](https://stackoverflow.com/questions/450620/change-the-ruby-process-name-in-top), [perl](https://stackoverflow.com/questions/18943142/how-do-i-change-the-process-name), [sh](https://stackoverflow.com/questions/3075682/how-to-set-the-process-name-of-a-shell-script)).

IMHO I don't like to try and patch up things that are so widespread, I'm thinking that this is just how running scripting language programs works.

If it annoys the hell out of you, you could make a pull request though :P

**Comment by aude** [comment]
If you're gonna implement it, https://pypi.org/project/setproctitle/ could indeed be the way to go. It tries to be cross platform, and looks more mature than the competition IMO.

There doesn't seems to be any built-in Python way to do this.

**Comment by skela** [comment]
https://github.com/aude/btlock/pull/2 pull request if you're interested. Let me know if you want stuff added, for example if you prefer this not to be done, I could make it a configurable thing. Although if you have multiple python scripts running, this is quite useful, as it lets you more easily see if btlock is running, and optionally kill it should the need arise.

**Comment by aude** [comment]
Yep, that's useful, let's merge it!
